### ISSUE TITLE
Complete various fixes

### ISSUE THREAD

**Issue by Unesdala** [WebJamApps/JaMmusic#125]
* [x] unit tests coverage is 100 percent for MusicPlayer/index
* [x] no codeclimate issues
* [x] snyk issues
* [x] fixes puppeteer to work with Core/Js and regenerator-runtime

**Comment by JoshuaVSherman** [comment]
@Unesdala FYI, be sure to set the pipeline for issues or it goes all the way to the far back of the board, thanks
