### ISSUE TITLE
common/utils has a throttle function, please refactor and unit test

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#15]
* refactor to eliminate the codeclimate complexity issue
* fully cover it with unit tests
* leave comment in app-main.js as to why we need this function

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman Throttling restricts the frequency of calls that a function receives to a fixed time interval. It is used to ensuring that the target function is not invoked more often than the specified delay.

Currently the `throttle` function is being used when you're resizing the page. the event handler is called more than 50 times in 2-3 seconds when you're resizing. this function prevents the event from being called frequently.

I had this function when I was building the `JamMusic` off `combined-front`.
It's not really used now. you can just remove it.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves ok thanks for explaining, please remove it then if it is not being used.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I'm also going to finish this task up today, thanks
