### ISSUE TITLE
YouTube and sound cloud styling to not display the play or pause embedded controls

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#194]
Utube has a Play button and a pause button in their video window (so does sound cloud), but I want to only have the user click our play/pause button so that there is not any issues with the player not running in continuous play mode when the song ends.

**Comment by Unesdala** [comment]
@JoshuaVSherman This one's kind of a tossup.

I have it now where YT's main play button isn't shown (Besides the giant one that always appears, regardless) but that also hides the other controls (Like volume and the total play time bar.) I can push it and you can check it out, though.

For Sound Cloud, any changes I make via CSS are being overwritten by the iframe. I can do it on a localized level through the inspection controls, but I can't figure out what to specify, if anything, in our CSS to be specific enough to bypass that. As is, there's nothing I can see in the API to change it either. At most, premium members can override the "Play on sound cloud" button that pops up in the mini player, but haven't found anything more than that.

The only other option I can find is making a custom player, but that seems a little overkill. Even then, I don't know how well that would play with iFrames - I would assume YT and SC would just override any options we implement. (https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Video_player_styling_basics)

**Comment by JoshuaVSherman** [comment]
@Unesdala https://www.techwalla.com/articles/how-to-disable-clicking-in-an-iframe

**Comment by JoshuaVSherman** [comment]
@Unesdala also place a white bar accross the youtube or soundcloud until the user clicks our `play` button, then remove that white bar so that there is no play button visible from those other players

**Comment by Unesdala** [comment]
@JoshuaVSherman Is that possible?

I know it should technically be possible to style the iFrame block, but from what I understand, that's more limited to size aspects, etc. Whereas trying to add in something over top of it is overridden by what's in the iFrame itself.

I can play around with it to try to add in a white bar, but it's not going to do much for Soundcloud given the play button doesn't display while playing.

**Comment by JoshuaVSherman** [comment]
@Unesdala for soundcloud, please display the white rectangle vertically to the left of the song title section , and for youtube, please make the white rectangle have more height so that is works with various screen sizes, thanks
