### ISSUE TITLE
After adding the Pub and/or Mission songs to the mix, clicking Shuffle does not work properly, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#199]

**Comment by Unesdala** [comment]
Can you explain what exactly isn't working properly? It seems to be working fine when testing, but may be expecting something different than what you are.

**Comment by Unesdala** [comment]
Oh, I see now.

When you click shuffle and then add in pub/mission, it's not shuffling the songs, it's defaulting to the original listings.

But adding them in and then clicking shuffle, it properly shuffles them.

**Comment by Unesdala** [comment]
Granted, clicking shuffle again (Which should be turning it off) will turn it on if you added pub/mission after hitting shuffle.

There's some weird updating going on with it.
