### ISSUE TITLE
puppeteer test for shopmain is failing, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#226]

**Comment by Unesdala** [comment]
I haven't found the exact cause of what's causing the issue, but I did find something interesting as to why it's just giving error.

For whatever reason, it can't navigate to the page to begin with.

Using await page.screenshot({ path: 'screenshot.png' });, I was able to get a shot of what it was seeing before ending the test.

![screenshot](https://user-images.githubusercontent.com/25317100/66743011-f65e3000-ee46-11e9-94d7-53c974536225.png)

Doesn't feel super useful, but it's at least something to go on from there. In hindsight, makes sense. Given it was returning Error for the page title and whatnot.

**Comment by Unesdala** [comment]
![screenshot1](https://user-images.githubusercontent.com/25317100/66743171-52c14f80-ee47-11e9-99a2-a2af92664a70.png)
That pulls a full screenshot of the page.

Might be useful for future debugging.

Now if I can figure out why it's not able to navigate to /shop, might be able to fix this.
