### ISSUE TITLE
Write unit test for full coverage of  src/containers/MusicDashboard index.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#235]

**Comment by JoshuaVSherman** [comment]
@Unesdala Good morning, I have not seen any progress on this issue for a while, please let me know if you want me to finish it and send you the merge request so you can see how I did it?

**Comment by Unesdala** [comment]
Was hoping to get feedback on what I had done, so I could see where I was going wrong. If you want to finish it out and send the merge request, though, that would achieve similar results.
