### ISSUE TITLE
Create an inquiry form for homepage

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#241]
* [ ] use validation for required fields
* [ ] submit button is disabled initially and enabled when form is valid
* [ ] music dashboard has example code to use
* [ ] submit should post to web-jam-back we will need to create a route for this the only accepts requests from our frontend

**Comment by JoshuaVSherman** [comment]
@Unesdala here you go, https://github.com/WebJamApps/JaMmusic/pull/248

**Comment by JoshuaVSherman** [comment]
@Unesdala what is the status of this please?

**Comment by Unesdala** [comment]
Just need the logic to be able to post to the backend (Which I'll need your help on, given I don't know what the code for the backend is like) and then finish up the few tests that are left, and then should be fully functional.

**Comment by Unesdala** [comment]
@JoshuaVSherman  There's still the if path for onChange and the handleChange event.

There's also the onChange function in statesDropDown (Which I'm guessing is interlinked with that if path?)

Everything else is tested for, but having issues with those. Mind taking a look?

**Comment by Unesdala** [comment]
I know handling the handleChange the same way as onChange (With the catch-all [evt.target.id]:) makes it work, and allows for proper testing like onChange uses, but doing that also makes comments flat out not change. So didn't see that as being an option, given how the form is being updated.
