### ISSUE TITLE
inquiry form post data properly to the backend

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#270]

**Comment by JoshuaVSherman** [comment]
@Unesdala good morning, any progress made on this please, also we can remove the hide for production on the form once it is posting correctly to the backend, thanks!

**Comment by Unesdala** [comment]
@JoshuaVSherman  yeah it was included in #270 albeit I don't know if it's working fully. Sent an email about it when I pushed the last bit of code.

Can you take a look at it? Code is in the emailAPI in inquiry

**Comment by Unesdala** [comment]
#269 rather, not #270
