### ISSUE TITLE
Add Wiki to JaMmusic github and update our getting started for developers google doc

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#304]
use notes from this issue as a starting point
https://github.com/WebJamApps/JaMmusic/issues/303

link to the more detailed google doc is https://docs.google.com/document/d/1_QDDbqmBrJuGqBoib59fmgYtls03dAXXuLqRR5roPO4/edit?usp=sharing

**Comment by Unesdala** [comment]
@JoshuaVSherman  - Given we're not currently working on, or including, OHAF, Jamcab, Library, or SC2RS, should those be omitted in System Requirements and Release Plan?

And if so, what all should be included? Just JaMmusic?

**Comment by JoshuaVSherman** [comment]
@Unesdala lets not worry about updating that one please, just the one I referenced with the link above, it it has a cross reference to the other one, just delete that link for now, thanks

I am mainly wanting someone new to understand that you need to have all three projects running locally in order to bring up the web-jam.com homepage locally, and you need various env variables, a connection to mongodb for dev and test, and if wanting to log into the site, a google developer's account with oauth2 setup

**Comment by JoshuaVSherman** [comment]
@Unesdala please let me know when you have good draft for the github wiki ready for me to review, thanks

**Comment by Unesdala** [comment]
@JoshuaVSherman - It's up and ready to review.

I know parts of it are going to need to be updated, but the bulk of it (That's still relevant) is there.
