### ISSUE TITLE
fix youtube white bar to hide play button that works on various screen sizes / resolutions

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#308]
does not work here is example

![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/b5597fc2-e446-4bb3-afca-402f3f86e858)

**Comment by Unesdala** [comment]
@JoshuaVSherman - Didn't know if this was still an issue, but I'm guessing it still is.

As a means of fixing this properly - Can you send your screen width?

**Comment by JoshuaVSherman** [comment]
all i did was zoom out to 80%, i'm sure you can figure it out, if not, let me know and then I will fix it myself, thanks
![image](https://user-images.githubusercontent.com/13340120/76212593-38658500-61df-11ea-9a48-a0df68529a40.png)
