### ISSUE TITLE
only on tablet width, logo is not the same width as the menu links, please fix (but don't mess up widescreen and cellphone displays)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#351]
![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/b4cc540b-121c-486a-8b88-32cc6cc5e41d)

**Comment by Unesdala** [comment]
@JoshuaVSherman What tablet size are you looking at this one? I've tried all the presets, and am not getting the same issue.
