### ISSUE TITLE
Minute section of Music Dashboard's time input is in a fixed state.

### ISSUE THREAD

**Issue by Unesdala** [WebJamApps/JaMmusic#418]
When attempting to change the time using the clock, hour can change, but the minute portion will default to whatever is in the current state.

IE: By default, it is 12:34. Changing that to any other time will leave it at [x]:34. IE: 1:34, 2:34, etc. regardless of what is chosen for the minute section.

Editing a tour will default to the tour's time-frame. IE: If the time set from edit was 1:00, it'll stay [x]:00. IE: 2:00, 3:00, etc.

Edit:

Manually editing the time via the minute button and clicking done properly sets time. It's solely when you select via the clock's face.

**Comment by JoshuaVSherman** [comment]
@Unesdala i'm assuming that you are stuck on how to fix this one, so I'll go ahead and take care of it

**Comment by JoshuaVSherman** [comment]
@Unesdala I am not able to reproduce this issue, possibly we already fixed it?
