### ISSUE TITLE
More fixes needed for mui-datatables

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#521]
`Could not load content for webpack:///./node_modules/mui-datatables/src/utils.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

```utils.js:21 Deprecation Notice:  scrollMaxHeight has been deprecated, but will still work in version 3.x. Please use string option: standard | vertical | simple. More info: https://github.com/gregnb/mui-datatables/tree/master/docs/v2_to_v3_guide.md
(anonymous) @ utils.js:21
DataTable.tsx:13 the tour table provider has been successfully connected :)
utils.js:21 Deprecation Notice:  scrollMaxHeight has been deprecated, but will still work in version 3.x. Please use string option: standard | vertical | simple. More info: https://github.com/gregnb/mui-datatables/tree/master/docs/v2_to_v3_guide.md```

**Comment by JoshuaVSherman** [comment]
@Unesdala was this fixed?

**Comment by Unesdala** [comment]
I know the second half of this was (Updating to the latest, and changing to standard.) I'm not sure if that fixed `Could not load content for webpack:///./node_modules/mui-datatables/src/utils.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME) `

**Comment by Unesdala** [comment]
As far as I can tell, both issues should be fixed now.
