### ISSUE TITLE
Tour table renders the href links into table cells

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#70]

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman you mean a column within the table is a link and is clickable?
Or you mean the link in embedded  within the text inside a column?

Regarding both of them, I'm not sure.

The best I've found is `https://github.com/gregnb/mui-datatables/issues/118`

And this applies to a row and `custom column rendering within MUI tables`.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I was hoping we could just loop though the data array and change the string to be and object that could be then rendered, for example
'Click <a href="somewhere.com">here</a> for more info.'
becomes {()=>(click <a href="somewhere.com">here</a>)}

I don't know the exact answer, I was hoping you could do some research and see what is the best way to have a data table for our project we can reuse it for all times we need a data table. I am not stuck on this particular react table package either. Also, if you don't find anything on your own or need me to work on this issue, it is okay to take your name off of it and pick up a different issue on the board.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves so yes, i'm trying to have a piece of text or a graphic or anything that is inside of the table cell be something that we can click to navigate someplace and the initial content comes from the json defining the table

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I have this one handled now, so you don't need to work on it, thanks
