### ISSUE TITLE
Add Song button remains disabled even though I have filled out the required fields, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#753]
- [ ] identified problem is the default for Category: `original` is not being captured as a default for the form validation

- [ ] in addition, the year should have a default value as the current year from Date object (not set as 2021)

![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/8b2629c6-717e-4ed3-94fe-bb385b4ecaf3)

**Comment by suhaill** [comment]
Can you please share your code so that I can help.

**Comment by JoshuaVSherman** [comment]
Although this is an open source project, I prefer to meet the developers
i'm working with before I give out any credentials. I am available tomorrow
if that works for you to hop on a zoom call?

**Comment by suhaill** [comment]
Yes sure. Let me know what time works for you. Thanks.

**Comment by JoshuaVSherman** [comment]
What is your email address?
Where are you located?
What kind of experience do you have developing React, Express, Mongodb?

**Comment by suhaill** [comment]
My email id is ***@***.***
I'm from Delhi. I have experience on PHP, Angular, JavaScript.
