### ISSUE TITLE
Adds two buttons to include/exclude 'mission' and 'pub' songs into the original music player

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#80]

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman could you add some description to this issue?

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves so on the /originals page, it loads the player with only the songs category='originals', then there are two more buttons under the player. If you click the Mission button, it should be green and now the player displays with category of both 'originals' and 'mission', unclick and it is back to only 'originals', the same thing for if you click the Pub button for this player

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I guess these two buttons cannot be `on` at the same time. when one is toggled, the other if off?

**Comment by JoshuaVSherman** [comment]
No you can turn on both at the same time

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves still waiting for ="button" to be fixed, thank you!
