### ISSUE TITLE
side menu scrolling with cell phone when open and exceeds height of cell phone

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#84]

**Comment by Unesdala** [comment]
@JoshuaVSherman - Do you have a screenshot or explanation of what specifically is happening with this?

**Comment by JoshuaVSherman** [comment]
@Unesdala good morning, so to explain this task in more details: you need to create some fake menu links and then look at the side menu when in cellphone mode using 320 x 480 and notice that the links have expanded beyond the display area. Then you need to make the side menu overflow scroll so that the user can move up the sidemenu to reach those links, you many need to prevent the menu from closing as well when the use is pushing the menu upwards, but i'm not sure on that, let me know if you need more details, thank you
