### ISSUE TITLE
JaMmusic new gig form won't submit

### ISSUE THREAD

**Issue by chemmom2** [WebJamApps/JaMmusic#871]
As a regular musician, the new gig form needs to create a gig on the list when I click the "create tour" button.

**Comment by chemmom2** [comment]
Ok, the plus sign is the new edit button; dashboard should be removed.

**Comment by JoshuaVSherman** [comment]
@chemmom2 yes I have removed it already, just didn't put it on production, so i'll remove this ticket now, lol
