### ISSUE TITLE
create a new homepage and use MUI to make it responsive layout (goal is to remove bootstrap)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#937]
https://mui.com/material-ui

- [x] use same content as current homepage
- [x] use cssgrid (not bootstrap, not flexbox, not media queries, not react resize detector), only CSS GRID !
- [x] The page should be responsive just like the current homepage (it does not need to be exactly the same breaks per width, it just should work as one would expect as someone drags the screen width smaller), for example the items should become 4 to 3 to 2 to 1 column (for the bottom section of the home page,  and from 2 to 1 column for the top section of the homepage

- [x] install docker on new laptop
- [x] install code climate on new laptop
- [x]  unit tests and code climate
- [x] manual test, need to fix cellphone displays and other width glitches
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0toQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1930cf24bc768221c85a98cdc1a49f22056c6a6/image.png)

- [ ]  after merge to master need to redeploy heroku apps and test on production (roll them back if tests fail)
- [ ]  test on production

**Comment by JoshuaVSherman** [comment]
https://github.com/WebJamApps/breakpointministries/blob/develop/static/layout/_blog.scss#L197

**Comment by kathleenahall** [comment]
I'll take a look yes
